### PR TITLE
Removed the duplicate title and fixed inner and static TOC links.

### LINKED ISSUE #87: Double element with page-title and TOC position
Hi,

When I generate my doc, I get two h1 with class 'page-title'. I think one is coming from layout.tmpl and the other from container.tmpl. Looks like the
````
<h1 class="page-title"><?js= title ?></h1>
````
in layout.tmpl is unnecessary as container.tmpl looks to be in charge of displaying the title.

There is another thing that looked weird, the actual TOC has a fixed position but it has right: 0px : in IE this is weird since the page content shows under the page scrollbar (unless you deactivate the IE scrollbar overlay by adding this to the html element in css):
````
html { -ms-overflow-style: scrollbar; }
```` 

Another solution would be to set it to right: 40px or so.

Thanks for the great work, your project makes the jsdoc much more user friendly and accessible.

### PR DESCRIPTION
**Pull request by Lochemage**
Fixes #87 and #83

### CODE REVIEW

**Comment by lukeapage** [comment]
@terryweiss any chance this can be pulled and a new release made? The double heading is the first thing you notice.. Thanks.

**Comment by petejohanson** [comment]
:+1: on getting this merged, this struck me immediately when starting to integrate JSDoc + DocStrap.

**Comment by AntoineGagnon** [comment]
Please merge this as soon as possible, this is really an annoying bug.. Thanks !

**Comment by gnstanley** [comment]
It seems that on a [later commit](https://github.com/terryweiss/docstrap/commit/c6e9d29307657e34805230818343657e38ca9c42#diff-1f2e6dffd9f034b975ed415f0220e336R50), the line was added back in.

**Comment by fisch0920** [comment]
I'm still seeing this as a problem with fresh projects and an up-to-date docstrap.

**Comment by obimod** [comment]
+1

**Comment by Pringels** [comment]
+1 Please fix this. It's quite an eye-sore.

**Pull request merged**
